"""save time and play count track

Revision ID: 89e9ace90992
Revises: 090eb6048777
Create Date: 2026-04-19 17:48:20.247262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89e9ace90992'
down_revision: Union[str, Sequence[str], None] = '090eb6048777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('play_count', sa.Integer(), nullable=True))
    op.add_column('tracks', sa.Column('last_position', sa.Integer(), nullable=True))
    op.add_column('tracks', sa.Column('last_played', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'last_played')
    op.drop_column('tracks', 'last_position')
    op.drop_column('tracks', 'play_count')
    # ### end Alembic commands ###
