"""add is_missing to tracks

Revision ID: b07d1bed41db
Revises: 89e9ace90992
Create Date: 2026-04-19 18:24:31.203500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b07d1bed41db'
down_revision: Union[str, Sequence[str], None] = '89e9ace90992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('is_missing', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'is_missing')
    # ### end Alembic commands ###
